version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: r3lixia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phishing-feed-tracker-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
