version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: r3lixia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phishing-feed-tracker-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .  # Assuming the Dockerfile is in the current directory
    restart: always
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis:6379/0  # Update this with the correct Redis URL
    command: ["./run.sh"]  # Update this if your run.sh script is located in a different path
