version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: r3lixia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phishing-feed-tracker-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .  
    restart: always
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis:6379/0  
    command: ["./run.sh"] 